

package es.unex.sextante.gui.core;

import java.util.HashMap;

import es.unex.sextante.dataObjects.ILayer;


/**
 * A class containing information needed to set rendering styles for layers generated by SEXTANTE geoalgorithms
 * 
 * @author volaya
 * 
 */
public interface IDataRenderer {

   public Object getRenderingForLayer(String sAlgCmdName,
                                      String sOutputName);


   public void setRenderingForAlgorithm(String sAlgCmdName,
                                        HashMap<String, Object> renderer);


   public void save();


   public void open();


   public Object getRenderingDataFromLayer(ILayer layer);

}
