package es.unex.sextante.gui.core;

import es.unex.sextante.core.GeoAlgorithm;
import es.unex.sextante.gui.additionalResults.AdditionalResults;

/**
 * Interface to be implemented by post process factories. A post process factory is used to define the task that should be
 * performed with algorithm results, once a SEXTANTE geoalgorithm has been executed from the SEXTANTE GUI
 * 
 * @author volaya
 * 
 */
public interface IPostProcessTaskFactory {

   /**
    * Returns a task to post-process the given algorithm. This task should take the outputs generated by the algorithm, adding
    * them to the GUI or doing with them whatever is needed.
    * 
    * To be compatible with the {@link AdditionalResults} class, charts and text result has to be added as java Components. Check
    * the documentation of that class for more information.
    * 
    * @param alg
    *                the algorithm to post-process
    * @param bShowResultsDialog
    *                if this parameter is true, the task will show the results dialog if the algorithm has produced some kind of
    *                output other than layers or tables. If it is false, those results will be added to the set of current
    *                results, but the results dialog will not be shown
    * @return a task to post-process the given algorithm
    */
   public Runnable getPostProcessTask(GeoAlgorithm alg,
                                      boolean bShowResultsDialog);


}
